name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Notify When VersionUp Action
        uses: shin-shin-01/notify-when-versionup-action@0.1
      - name: print to debug
        run: pwd | ls -a
