name: notify-when-versionup-action

on:
  schedule:
    # 毎日 11:00 (JST) に処理を実行する。
    # UTC 02:00 -> JST 11:00
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Notify When VersionUp action
        uses: shin-shin-01/notify-when-versionup-action@1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          DEFAULT_BRANCH: ${{ github.ref }}
  