name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github repository
        run: echo ${{ github.repository }}
      - name: Echo github event
        run: echo ${{ github.event }}
  